"""
PDF Generator Utility
Generates PDF reports with table formatting for the Healthcare Management System
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
import os

class PDFReportGenerator:
    """Generate PDF reports with professional table formatting"""
    
    def __init__(self, filename, title="Healthcare Management System Report"):
        """
        Initialize PDF generator
        
        Args:
            filename: Output PDF filename
            title: Report title
        """
        self.filename = filename
        self.title = title
        self.doc = SimpleDocTemplate(
            filename,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        self.story = []
        self.styles = getSampleStyleSheet()
        
        # Custom styles
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#2E86AB'),
            spaceAfter=30,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        )
        
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#111827'),
            spaceAfter=12,
            spaceBefore=12,
            fontName='Helvetica-Bold'
        )
        
        self.subheading_style = ParagraphStyle(
            'CustomSubHeading',
            parent=self.styles['Heading3'],
            fontSize=12,
            textColor=colors.HexColor('#6B7280'),
            spaceAfter=8,
            fontName='Helvetica'
        )
        
        self.normal_style = ParagraphStyle(
            'CustomNormal',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#111827'),
            spaceAfter=6,
            fontName='Helvetica'
        )
    
    def add_title(self, title=None):
        """Add report title"""
        title_text = title or self.title
        self.story.append(Paragraph(title_text, self.title_style))
        self.story.append(Spacer(1, 0.2*inch))
    
    def add_header_info(self, admin_name, report_type="General Report"):
        """Add header information"""
        header_data = [
            ['Report Type:', report_type],
            ['Hospital Name:', 'Baylor Scott'],
            ['Generated By:', admin_name],
            ['Generated On:', datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            ['System:', 'Healthcare Management System']
        ]
        
        header_table = Table(header_data, colWidths=[2*inch, 4*inch])
        header_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F8FAFC')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#111827')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB'))
        ]))
        
        self.story.append(header_table)
        self.story.append(Spacer(1, 0.3*inch))
    
    def add_table(self, data, headers, title=None):
        """
        Add a formatted table to the PDF
        
        Args:
            data: List of lists containing table data
            headers: List of column headers
            title: Optional table title
        """
        if title:
            self.story.append(Paragraph(title, self.heading_style))
            self.story.append(Spacer(1, 0.1*inch))
        
        # Prepare table data with headers
        table_data = [headers] + data
        
        # Calculate column widths (distribute evenly or based on content)
        num_cols = len(headers)
        available_width = 6.5 * inch  # Total width minus margins
        col_width = available_width / num_cols
        
        # Create table
        table = Table(table_data, colWidths=[col_width] * num_cols, repeatRows=1)
        
        # Apply table style
        table.setStyle(TableStyle([
            # Header row style
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2E86AB')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('TOPPADDING', (0, 0), (-1, 0), 12),
            
            # Data rows style
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#111827')),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
            ('TOPPADDING', (0, 1), (-1, -1), 8),
            
            # Grid lines
            ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#E5E7EB')),
            ('LINEBELOW', (0, 0), (-1, 0), 2, colors.HexColor('#2E86AB')),
            
            # Alternating row colors
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8FAFC')]),
            
            # Alignment adjustments
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ]))
        
        self.story.append(table)
        self.story.append(Spacer(1, 0.3*inch))
    
    def add_paragraph(self, text, style=None):
        """Add a paragraph of text"""
        style = style or self.normal_style
        self.story.append(Paragraph(text, style))
        self.story.append(Spacer(1, 0.1*inch))
    
    def add_heading(self, text):
        """Add a heading"""
        self.story.append(Paragraph(text, self.heading_style))
        self.story.append(Spacer(1, 0.15*inch))
    
    def add_subheading(self, text):
        """Add a subheading"""
        self.story.append(Paragraph(text, self.subheading_style))
        self.story.append(Spacer(1, 0.1*inch))
    
    def add_page_break(self):
        """Add a page break"""
        self.story.append(PageBreak())
    
    def add_summary_section(self, summary_data):
        """Add a summary section with key-value pairs"""
        summary_items = []
        for key, value in summary_data.items():
            summary_items.append([key, str(value)])
        
        summary_table = Table(summary_items, colWidths=[2.5*inch, 4*inch])
        summary_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F8FAFC')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#111827')),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E5E7EB'))
        ]))
        
        self.story.append(Paragraph("Summary", self.heading_style))
        self.story.append(summary_table)
        self.story.append(Spacer(1, 0.3*inch))
    
    def build(self):
        """Build and save the PDF"""
        self.doc.build(self.story)
        return self.filename


def generate_doctor_patient_pdf(filename, admin_name, doctor_data):
    """
    Generate PDF report for doctor-wise patient count
    
    Args:
        filename: Output PDF filename
        admin_name: Name of administrator generating the report
        doctor_data: List of dictionaries with doctor information
    """
    generator = PDFReportGenerator(filename, "Doctor-wise Patient Count Report")
    
    # Add title
    generator.add_title()
    
    # Add header info
    generator.add_header_info(admin_name, "Doctor-wise Patient Count Report")
    
    # Prepare table data
    if doctor_data:
        headers = ["Doctor Name", "Specialization", "Total Patients"]
        table_data = []
        for doctor in doctor_data:
            table_data.append([
                doctor.get('doctor_name', 'N/A'),
                doctor.get('specialization', 'N/A'),
                str(doctor.get('patient_count', 0))
            ])
        
        generator.add_table(table_data, headers, "Doctor Patient Statistics")
        
        # Add summary
        total_patients = sum(d.get('patient_count', 0) for d in doctor_data)
        total_doctors = len(doctor_data)
        summary = {
            "Total Doctors": total_doctors,
            "Total Patients Served": total_patients,
            "Average Patients per Doctor": round(total_patients / total_doctors, 2) if total_doctors > 0 else 0
        }
        generator.add_summary_section(summary)
    else:
        generator.add_paragraph("No doctor data available.", generator.normal_style)
    
    # Build PDF
    return generator.build()


def generate_system_summary_pdf(filename, admin_name, stats):
    """
    Generate PDF report for system usage summary
    
    Args:
        filename: Output PDF filename
        admin_name: Name of administrator generating the report
        stats: Dictionary with system statistics
    """
    generator = PDFReportGenerator(filename, "System Usage Summary Report")
    
    # Add title
    generator.add_title()
    
    # Add header info
    generator.add_header_info(admin_name, "System Usage Summary Report")
    
    # System Statistics Table
    stats_data = [
        ["Total Patients", str(stats.get('total_patients', 0))],
        ["Total Doctors", str(stats.get('total_doctors', 0))],
        ["Total Nurses", str(stats.get('total_nurses', 0))],
        ["Active Prescriptions", str(stats.get('active_prescriptions', 0))]
    ]
    
    generator.add_table(stats_data, ["Category", "Count"], "System Statistics")
    
    # System Health Summary
    health_summary = {
        "System Status": "Operational",
        "Database Status": "Connected",
        "Last Backup": datetime.now().strftime('%Y-%m-%d'),
        "Report Generated": datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }
    generator.add_summary_section(health_summary)
    
    # Build PDF
    return generator.build()


def generate_user_activity_pdf(filename, admin_name, users):
    """
    Generate PDF report for user activity
    
    Args:
        filename: Output PDF filename
        admin_name: Name of administrator generating the report
        users: List of user dictionaries
    """
    generator = PDFReportGenerator(filename, "User Activity Report")
    
    # Add title
    generator.add_title()
    
    # Add header info
    generator.add_header_info(admin_name, "User Activity Report")
    
    # Calculate role distribution
    role_counts = {}
    active_counts = {}
    
    for user in users:
        role = user.get('role', 'unknown')
        role_counts[role] = role_counts.get(role, 0) + 1
        if user.get('is_active', False):
            active_counts[role] = active_counts.get(role, 0) + 1
    
    # Role Distribution Table
    role_data = []
    for role in ['admin', 'doctor', 'nurse', 'patient']:
        total = role_counts.get(role, 0)
        active = active_counts.get(role, 0)
        inactive = total - active
        role_data.append([
            role.title(),
            str(total),
            str(active),
            str(inactive)
        ])
    
    generator.add_table(
        role_data,
        ["Role", "Total Users", "Active", "Inactive"],
        "User Distribution by Role"
    )
    
    # User Details Table (sample of first 20 users)
    if users:
        user_headers = ["Username", "Full Name", "Email", "Role", "Status"]
        user_data = []
        for user in users[:20]:  # Limit to first 20 for readability
            user_data.append([
                user.get('username', 'N/A'),
                user.get('full_name', 'N/A'),
                user.get('email', 'N/A'),
                user.get('role', 'N/A').title(),
                "Active" if user.get('is_active', False) else "Inactive"
            ])
        
        generator.add_table(user_data, user_headers, "User Details (Sample)")
        
        if len(users) > 20:
            generator.add_paragraph(
                f"Note: Showing first 20 users out of {len(users)} total users.",
                generator.normal_style
            )
    
    # Summary
    total_users = len(users)
    total_active = sum(1 for u in users if u.get('is_active', False))
    summary = {
        "Total Users": total_users,
        "Active Users": total_active,
        "Inactive Users": total_users - total_active,
        "Report Generated": datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }
    generator.add_summary_section(summary)
    
    # Build PDF
    return generator.build()


def generate_dashboard_pdf(filename, admin_name, stats, doctor_data=None):
    """
    Generate comprehensive dashboard PDF report
    
    Args:
        filename: Output PDF filename
        admin_name: Name of administrator generating the report
        stats: Dictionary with system statistics
        doctor_data: Optional list of doctor data
    """
    generator = PDFReportGenerator(filename, "Administrator Dashboard Report")
    
    # Add title
    generator.add_title()
    
    # Add header info
    generator.add_header_info(admin_name, "Comprehensive Dashboard Report")
    
    # System Overview Table
    overview_data = [
        ["Total Patients", str(stats.get('total_patients', 0))],
        ["Total Doctors", str(stats.get('total_doctors', 0))],
        ["Total Nurses", str(stats.get('total_nurses', 0))],
        ["Active Prescriptions", str(stats.get('active_prescriptions', 0))]
    ]
    
    generator.add_table(overview_data, ["Metric", "Value"], "System Overview")
    
    # Doctor Performance (if available)
    if doctor_data:
        headers = ["Doctor Name", "Specialization", "Total Patients"]
        table_data = []
        for doctor in doctor_data:
            table_data.append([
                doctor.get('doctor_name', 'N/A'),
                doctor.get('specialization', 'N/A'),
                str(doctor.get('patient_count', 0))
            ])
        generator.add_table(table_data, headers, "Doctor Performance Summary")
    
    # System Health Summary
    health_summary = {
        "System Status": "Operational",
        "Database Status": "Connected",
        "Report Generated": datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        "Generated By": admin_name
    }
    generator.add_summary_section(health_summary)
    
    # Build PDF
    return generator.build()

